project:
  type: book

book:
  title: "Emprendimiento con Datos en Turismo"
  author: "Francisco J. Navarro-Meneses, Editor"
  date: "5/10/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - 1_turismo_datos_emprendimiento.qmd
    - 2_metodos_tecnologias.qmd
    - 3_proceso.qmd
    - 4_practicas_gestion.qmd
    - 5_oportunidades.qmd
    - 6_Ã©tica.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

